/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.24.2
// source: msg.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./msg_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ChatServerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ChatServerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Empty,
 *   !proto.ChatMessage>}
 */
const methodDescriptor_ChatServer_ChatStream = new grpc.web.MethodDescriptor(
  '/ChatServer/ChatStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.Empty,
  proto.ChatMessage,
  /**
   * @param {!proto.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ChatMessage.deserializeBinary
);


/**
 * @param {!proto.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.ChatMessage>}
 *     The XHR Node Readable Stream
 */
proto.ChatServerClient.prototype.chatStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ChatServer/ChatStream',
      request,
      metadata || {},
      methodDescriptor_ChatServer_ChatStream);
};


/**
 * @param {!proto.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.ChatMessage>}
 *     The XHR Node Readable Stream
 */
proto.ChatServerPromiseClient.prototype.chatStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ChatServer/ChatStream',
      request,
      metadata || {},
      methodDescriptor_ChatServer_ChatStream);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ChatMessage,
 *   !proto.Empty>}
 */
const methodDescriptor_ChatServer_SendChatMessage = new grpc.web.MethodDescriptor(
  '/ChatServer/SendChatMessage',
  grpc.web.MethodType.UNARY,
  proto.ChatMessage,
  proto.Empty,
  /**
   * @param {!proto.ChatMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Empty.deserializeBinary
);


/**
 * @param {!proto.ChatMessage} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ChatServerClient.prototype.sendChatMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ChatServer/SendChatMessage',
      request,
      metadata || {},
      methodDescriptor_ChatServer_SendChatMessage,
      callback);
};


/**
 * @param {!proto.ChatMessage} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Empty>}
 *     Promise that resolves to the response
 */
proto.ChatServerPromiseClient.prototype.sendChatMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ChatServer/SendChatMessage',
      request,
      metadata || {},
      methodDescriptor_ChatServer_SendChatMessage);
};


module.exports = proto;

